# Generated by Django 4.2.7 on 2025-08-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
